<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>MERSEL.Services.HtmlToPdf.Tests.Shared</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="PdfSharpCore" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Samples\*.html" />
  </ItemGroup>

</Project>
